-- MySQL Script generated by MySQL Workbench
-- Fri Mar 22 10:21:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sharepic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sharepic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sharepic` DEFAULT CHARACTER SET utf8 ;
USE `sharepic` ;

-- -----------------------------------------------------
-- Table `sharepic`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharepic`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ids` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `registered_at` DATETIME NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharepic`.`avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharepic`.`avatar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `local_uri` VARCHAR(255) NOT NULL,
  `added_at` DATETIME NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharepic`.`publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharepic`.`publication` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ids` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  `geolocation` VARCHAR(45) NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharepic`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharepic`.`photo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `local_uri` VARCHAR(45) NOT NULL,
  `fingerprint` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharepic`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharepic`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `added_at` DATETIME NOT NULL,
  `Publication_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharepic`.`reaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharepic`.`reaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image_uri` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharepic`.`publication_reaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharepic`.`publication_reaction` (
  `Publication_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `reacted_at` DATETIME NOT NULL,
  `Reaction_id` INT NOT NULL,
  PRIMARY KEY (`Publication_id`, `User_id`, `Reaction_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharepic`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharepic`.`subscription` (
  `Subscribed_User_id` INT NOT NULL,
  `Subscriber_User_id` INT NOT NULL,
  `subscribed_at` DATETIME NOT NULL,
  PRIMARY KEY (`Subscribed_User_id`, `Subscriber_User_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharepic`.`conversation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharepic`.`conversation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharepic`.`conversation_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharepic`.`conversation_has_user` (
  `User_id` INT NOT NULL,
  `Conversation_id` INT NOT NULL,
  `added_at` DATETIME NOT NULL,
  PRIMARY KEY (`User_id`, `Conversation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharepic`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharepic`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(1000) NOT NULL,
  `Conversation_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `added_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharepic`.`connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharepic`.`connection` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `ip` VARCHAR(45) NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharepic`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharepic`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(255) NOT NULL,
  `Publication_id` INT NULL,
  `Target_User_id` INT NULL,
  `seen` TINYINT NOT NULL DEFAULT 0,
  `User_id` INT NOT NULL,
  `added_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sharepic`.`publication_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sharepic`.`publication_photo` (
  `Publication_id` INT NOT NULL,
  `Photo_id` INT NOT NULL,
  `order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Publication_id`, `Photo_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
