version: "3"
services:
  #PHP Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: sharepic_api
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www/api.sharepic.net
      - ./api/php.local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - sharepic-network
    links:
      - database

  #Nginx Service
  nginx:
    build:
      context: ./api
      dockerfile: Dockerfile_nginx
    container_name: sharepic_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./api:/var/www/api.sharepic.net
      - ./api/sharepic.nginx.conf:/etc/nginx/conf.d/sharepic.nginx.conf
    networks:
      - sharepic-network

  #MySQL Service
  database:
    image: mysql:5.7.22
    container_name: sharepic_database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sharepic
      MYSQL_ROOT_PASSWORD: sharepic_root_password
      MYSQL_USER: sharepic_user
      MYSQL_PASSWORD: sharepic_password
    volumes:
      - database:/var/lib/mysql
      - ./api/mysql.my.cnf:/etc/mysql/my.cnf
      - ./api/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - sharepic-network

#Docker Networks
networks:
  sharepic-network:
    driver: bridge

volumes:
    database:
