-- MySQL Script generated by MySQL Workbench
-- Mon Mar 18 13:12:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ids` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `registered_at` DATETIME NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avatar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `local_uri` VARCHAR(255) NOT NULL,
  `added_at` DATETIME NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`),
  INDEX `fk_Avatar_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Avatar_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publication` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ids` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  `geolocation` VARCHAR(45) NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`),
  INDEX `fk_Publication_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Publication_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Photo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `local_uri` VARCHAR(45) NOT NULL,
  `order` INT NOT NULL DEFAULT 0,
  `fingerprint` VARCHAR(255) NOT NULL,
  `Publication_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Publication_id`),
  INDEX `fk_Photo_Publication_idx` (`Publication_id` ASC) VISIBLE,
  CONSTRAINT `fk_Photo_Publication`
    FOREIGN KEY (`Publication_id`)
    REFERENCES `mydb`.`Publication` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `added_at` DATETIME NOT NULL,
  `Publication_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comment_Publication1_idx` (`Publication_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_Publication1`
    FOREIGN KEY (`Publication_id`)
    REFERENCES `mydb`.`Publication` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image_uri` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publication_Reaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publication_Reaction` (
  `Publication_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `reacted_at` DATETIME NOT NULL,
  `Reaction_id` INT NOT NULL,
  PRIMARY KEY (`Publication_id`, `User_id`, `Reaction_id`),
  INDEX `fk_Publication_has_User_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Publication_has_User_Publication1_idx` (`Publication_id` ASC) VISIBLE,
  INDEX `fk_React_Reaction1_idx` (`Reaction_id` ASC) VISIBLE,
  CONSTRAINT `fk_Publication_has_User_Publication1`
    FOREIGN KEY (`Publication_id`)
    REFERENCES `mydb`.`Publication` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Publication_has_User_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_React_Reaction1`
    FOREIGN KEY (`Reaction_id`)
    REFERENCES `mydb`.`Reaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subscription` (
  `Subscribed_User_id` INT NOT NULL,
  `Subscriber_User_id` INT NOT NULL,
  `subscribed_at` DATETIME NOT NULL,
  PRIMARY KEY (`Subscribed_User_id`, `Subscriber_User_id`),
  INDEX `fk_User_has_User_User2_idx` (`Subscriber_User_id` ASC) VISIBLE,
  INDEX `fk_User_has_User_User1_idx` (`Subscribed_User_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_User_User1`
    FOREIGN KEY (`Subscribed_User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_User_User2`
    FOREIGN KEY (`Subscriber_User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conversation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conversation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conversation_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conversation_has_User` (
  `User_id` INT NOT NULL,
  `Conversation_id` INT NOT NULL,
  `added_at` DATETIME NOT NULL,
  PRIMARY KEY (`User_id`, `Conversation_id`),
  INDEX `fk_User_has_Conversation_Conversation1_idx` (`Conversation_id` ASC) VISIBLE,
  INDEX `fk_User_has_Conversation_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Conversation_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Conversation_Conversation1`
    FOREIGN KEY (`Conversation_id`)
    REFERENCES `mydb`.`Conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  `Conversation_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Message_Conversation1_idx` (`Conversation_id` ASC) VISIBLE,
  INDEX `fk_Message_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Message_Conversation1`
    FOREIGN KEY (`Conversation_id`)
    REFERENCES `mydb`.`Conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
